- Makefile
- README.md
- community_meetings/settings.py
- local_run.sh
- manage.py
- meetings/views.py
- requirements.txt
> Support local development

- meetings/management/commands/handle_recordings.py
When a file had been uploaded to OBS, it'll just satisfy the judge in line 211 and do unless operations. So change `if` to `elif`.
> reduce unless operations

- meetings/management/commands/genegroup.py
- meetings/management/commands/handle_recordings.py
capture README.md when locating sigs cause of the same dir level, skipped it already.
> fix the bug that README.md appear in sigs list

- templates/get_templates.py
Reverts opensourceways/app-meeting-server#133
> Revert "modify html templates based on the table label"

- meetings/utils/maillist_mapping.yaml
add mapping of mailing list for SIG Plugin
> add mapping for SIG Plugin

- meetings/management/commands/genegroup.py
fix the scheduled task failure caused by domain name change
> adapt to new domain name

- meetings/send_email.py
- templates/template_with_summary_with_recordings.txt
- templates/template_with_summary_without_recordings.txt
- templates/template_without_summary_with_recordings.txt
- templates/template_without_summary_without_recordings.txt
Add 4 text templates and change hypertext to text in send_email for sending text messages
> send email through text instead of hypertext

- meetings/utils/prepare_create_activity.py
support only online activity for MSG activity
> remove restructions on MSG activity types

- meetings/management/commands/genegroup.py
Find some sig has no OWNERS file so support get maintainers from sig-info.yaml
> adapte to sig-info.yaml when updating sigs info

- meetings/management/commands/genegroup.py
- meetings/send_email.py
1. add calendar when booking meetings
2. fix issues about updating sigs info
> send email with calendar and fix a issue about genegroup

- requirements.txt
replenish the missing dependency icalendar
> add requirement

- meetings/send_email.py
- meetings/views.py
fix issue that end is not defined
> add parameter end for sendmail

- meetings/urls.py
- meetings/views.py
The one is a queryset of meetings, and the other is a queryset of activities.
> add 2 interfaces for website calendar

- community_meetings/settings.py
- meetings/models.py
- meetings/send_email.py
- meetings/serializers.py
- meetings/utils/drivers.py
- meetings/utils/welink_apis.py
- meetings/utils/zoom_apis.py
- meetings/views.py
- templates/template_with_summary_with_recordings.txt
- templates/template_with_summary_without_recordings.txt
- templates/template_without_summary_with_recordings.txt
- templates/template_without_summary_without_recordings.txt
1. Meeting新增mplatform字段以区分不同平台的会议
2. 调整settings.MEETING_HOSTS层级结构
3. meetings/views中创建会议、删除会议、查询参会者的逻辑在meetings/utils下新增drivers，zoom_apis，welink_apis实现
4. 微调邮件模板以及发送邮件函数的变量
> support welink meeting

- community_meetings/settings.py
- meetings/management/commands/handle_recordings.py
- meetings/utils/welink_apis.py
- meetings/views.py
1. 调整cronjob handle_recordings，适配welink云录制的下载、上传
2. 调整welink的会议参会者查询接口，返回通过该会议id查询到的所有片段的参会者
3. 调整welink的创建会议接口云录制的参数
4. welink新增查询录像列表、查询录像下载地址、下载welink云录制视频 3个接口
5. 优化了官网会议日历的时间范围，并新增了会议平台的标记字段
6. 调整welink账号配置结构
7. 修复管理员无法删除其他预订者预定的会议的bug
> support cloud recording for welink

- meetings/models.py
- meetings/send_email.py
- meetings/serializers.py
- meetings/utils/drivers.py
- meetings/utils/tecent_apis.py
- meetings/utils/welink_apis.py
- meetings/views.py
- mindspore_meetings/settings.py
- templates/template_with_summary_with_recordings.txt
- templates/template_with_summary_without_recordings.txt
- templates/template_without_summary_with_recordings.txt
- templates/template_without_summary_without_recordings.txt
1. Meeting Model新增mplatform字段
2. 修改邮件模板和send_email
3. 新增meetings.utils.drviers, meetings.utils.welink_apis, 扩展meetings.utils.tecent_apis
4. settings调整HOSTS映射
5. 调整meetings.views
> support welink meetings

- meetings/urls.py
- meetings/views.py
openEuler官网SIG数据获取来源发生变化，故将SIG的会议数据改为通过SIG名访问而非SIG的id
> modify interface about getting meetingsdata of a sig

- meetings/urls.py
- meetings/views.py
> add a interface about showing activities calendar data

- meetings/utils/send_applicants_info.py
修复在活动发起者导出的报名者表单中，已签到的报名者显示未签到的问题
> fix issue that cannot mark people who signed

- meetings/management/commands/genegroup.py
> stop getting mailist of sigs

- meetings/utils/send_applicants_info.py
- meetings/utils/send_cancel_email.py
- meetings/utils/send_feedback.py
- meetings/utils/send_start_url.py
> modify how to send mail in other scenarios

- meetings/send_email.py
- meetings/views.py
> add issue location output

- meetings/send_email.py
- meetings/views.py
1. 去除调试日志
2. 修改send_email.sendmail的第一个传参为一个包含meeting必要信息的字典而非mid，避免在子进程中进行数据库查询
> modify the first parameter of sending mail and remove test log

- meetings/send_email.py
- meetings/views.py
> avoid connect database when start a child process

- meetings/views.py
> fix undefined issue about updating meetings

- Dockerfile
wkhtmltox-0.12.3不再可用，升级版本为0.12.6
> fix issue that cannot generate thumbnails

- Dockerfile
- meetings/auth.py
- meetings/send_email.py
- meetings/serializers.py
- meetings/utils/gene_sign_code.py
- meetings/utils/gene_wx_code.py
- meetings/utils/send_applicants_info.py
- meetings/utils/send_cancel_email.py
- meetings/utils/send_feedback.py
- meetings/utils/send_recording_completed_msg.py
- meetings/utils/welink_apis.py
- meetings/views.py
- mindspore_meetings/urls.py
1. 清除codecheck相关问题
2. 新增jwtToken刷新和过期机制，预防重放攻击
> change for icsl

- Dockerfile
- meetings/__init__.py
- meetings/serializers.py
- requirements.txt
Update base image cause openeuler/openeuler:21.03 has been deprecated
> upgrade base image

- meetings/models.py
- meetings/views.py
- opengauss_meetings/settings.py
1. User新增expire_time标记字段
2. 重命名access_token在cookie中的键名
> add mark for loging out

- community_meetings/settings.py
> replace the meeting hosts

- Dockerfile
- meetings/management/commands/genegroup.py
- meetings/permissions.py
- meetings/send_email.py
- meetings/utils/gene_sign_code.py
- meetings/utils/gene_wx_code.py
- meetings/utils/send_applicants_info.py
- meetings/utils/send_cancel_email.py
- meetings/utils/send_feedback.py
- meetings/utils/send_recording_completed_msg.py
- meetings/views.py
- mindspore_meetings/settings.py
> fix exist issues

- mindspore_meetings/settings.py
> remove rasp config

- Dockerfile
- opengauss_meetings/settings.py
- opengauss_meetings/wsgi.py
1. 解决因 !264 产生的冲突
2. 使用端到端认证获取Oauth token替代JWT token
3. 配置路径参数化
> change the way to get zoom token

- meetings/utils/tecent_apis.py
- mindspore_meetings/settings.py
> remove 2 hosts

- community_meetings/settings.py
- meetings/management/commands/handle_recordings.py
- meetings/management/commands/update_access.py
- meetings/models.py
- meetings/utils/invite.py
- meetings/utils/zoom_apis.py
因使用account_credentials获取令牌意外失效，改为使用Oauth2.0 获取、刷新令牌
> fix token grant issue

- meetings/management/commands/handle_recordings.py
- meetings/management/commands/update_access.py
- meetings/models.py
- meetings/utils/zoom_apis.py
- opengauss_meetings/settings.py
因使用account_credentials获取令牌意外失效，改为使用Oauth2.0 获取、刷新令牌
> fix token authorize issue

- opengauss_meetings/settings.py
> remove DB default

- opengauss_meetings/settings.py
> parameterize DB_NAME

- app_meeting_server/utils/bilibili_apis/__init__.py
- app_meeting_server/utils/bilibili_apis/channel_series.py
- app_meeting_server/utils/bilibili_apis/credential.py
- app_meeting_server/utils/bilibili_apis/data/api/credential.json
- app_meeting_server/utils/bilibili_apis/data/api/dynamic.json
- app_meeting_server/utils/bilibili_apis/data/api/user.json
- app_meeting_server/utils/bilibili_apis/data/api/video_uploader.json
- app_meeting_server/utils/bilibili_apis/dynamic.py
- app_meeting_server/utils/bilibili_apis/exceptions/ApiException.py
- app_meeting_server/utils/bilibili_apis/exceptions/CredentialNoAcTimeValueException.py
- app_meeting_server/utils/bilibili_apis/exceptions/CredentialNoBiliJctException.py
- app_meeting_server/utils/bilibili_apis/exceptions/CredentialNoBuvid3Exception.py
- app_meeting_server/utils/bilibili_apis/exceptions/CredentialNoDedeUserIDException.py
- app_meeting_server/utils/bilibili_apis/exceptions/CredentialNoSessdataException.py
- app_meeting_server/utils/bilibili_apis/exceptions/NetworkException.py
- app_meeting_server/utils/bilibili_apis/exceptions/ResponseCodeException.py
- app_meeting_server/utils/bilibili_apis/exceptions/__init__.py
- app_meeting_server/utils/bilibili_apis/settings.py
- app_meeting_server/utils/bilibili_apis/user.py
- app_meeting_server/utils/bilibili_apis/utils/AsyncEvent.py
- app_meeting_server/utils/bilibili_apis/utils/__init__.py
- app_meeting_server/utils/bilibili_apis/utils/credential.py
- app_meeting_server/utils/bilibili_apis/utils/network.py
- app_meeting_server/utils/bilibili_apis/utils/picture.py
- app_meeting_server/utils/bilibili_apis/utils/sync.py
- app_meeting_server/utils/bilibili_apis/utils/utils.py
- app_meeting_server/utils/bilibili_apis/video_uploader.py
- requirements.txt
1.add bilibili_apis
2.refresh requirements
> add bilibili_apis

- app_meeting_server/utils/bilibili_apis/utils/network.py
fix import error cause report TypeError
> fix import error cause report TypeError

- app_meeting_server/settings/prod.py
> add a host for welink meetings

- app_meeting_server/apps/openeuler/views.py
> fix issue about mismatch data type searching

- app_meeting_server/apps/mindspore/utils/drivers.py
- app_meeting_server/apps/mindspore/utils/tencent_apis.py
- app_meeting_server/apps/openeuler/utils/tencent_apis.py
- app_meeting_server/apps/openeuler/utils/welink_apis.py
- app_meeting_server/apps/opengauss/utils/welink_apis.py
- app_meeting_server/apps/opengauss/views.py
- app_meeting_server/utils/zoom_apis.py
1. 统一多个平台查询会议参会者的数据结构
2. openGauss查询allmeetings时添加分页器
3. mindspore会议移除多余代码
> unified data structure
