opensourceways/app-meeting-server

- meetings/management/commands/sendmessages.py
- meetings/views.py
在小程序订阅消息参数值内容限制说明中，thing.DATA的长度限制为20个字符，当传入参数过长时，会报47003的错误。详见
https://developers.weixin.qq.com/miniprogram/dev/api-backend/open-api/subscribe-message/subscribeMessage.send.html 中订阅消息参数值内容限制说明。因此当topic长度大于20字符时，截取前20个字符传入模板，能做到不影响小程序上topic的显示，又能给创建者和收藏者发送推送消息。
> limit the length of topic

- mindspore_meetings/urls.py
Remove the prefix of route when separated from other servers because it's no longer meaningful
> remove the prefix of route

- requirements.txt
In past builds, tzlocal was built as verision 2.1 but the last was 3.0 which may lead dependency conflict. So limit the version of tzlocal.
> limit tzlocal<3.0 to avoid dependency conflict

- meetings/serializers.py
- meetings/views.py
1. extend `telephone` and `email` fields for showing sponsors and updating sponsor info
2. return collection_id after collecting a meeting successfully to satisfy the collection status change
> extend fields for sponsors list and update interfaces, add collection id

- meetings/views.py
Repalce MeetingDetailSerializer with MeetingsListSerializer instead of showing useless fields.
> use MeetingsListSerializer instead of serializer what shows every field

- meetings/send_email.py
Although the sending list adds the list by rule, the attendee of  the calendar cannot be added. Change the scope so that new recipients can also receive the calendar that is displayed normally.
> fix issue that cc cannot attach calendari automatically

- meetings/send_email.py
- meetings/utils/send_cancel_email.py
- meetings/views.py
- templates/template_cancel_meeting.txt
1. 优化meetings.send_email.sendmail的入参
2. 拓宽calendar的attendee的范围，防止attendee为空，生成 not supported calendar message.ics
3. 同一个会议固定uid，避免在日历上多次加载
4. 提醒时间恢复为默认的会议开始前15分钟
5. 新增取消会议发送邮件通知
6. 邮箱正则匹配调整，支持前缀包含'+', '.'
> calendar optimization

- meetings/send_email.py
- meetings/utils/send_cancel_email.py
Stop Bcc sending when creating or cancelling a meeting and exit early when the valid recipient is 0.
> cancel Bcc

- meetings/send_email.py
- meetings/utils/send_cancel_email.py
预定openGauss会议时系统会默认发给sig组对应的邮件列表，在取消会议时邮件收件人也应与预定的保持一致
> unify mail sending list

- meetings/serializers.py
Add field `maillist` when searching a user's SIGS info
> support identification of SIG maillist automatically

- community_meetings/settings.py
- community_meetings/urls.py
- requirements.txt
1. 升级djangorestframework的版本，将jQuery版本升至3.5.1
2. 处理依赖，将Django版本升至2.2
3. 考虑到drf_yasg作为接口调试工具，在生产环境无实际意义，且升级djangorestframework后drf_yasg会报导包错误，故将其移除
> upgrade restframework to fix security vulnerability

- meetings/__init__.py
通过在meetings/__init__.py中声明pymysql的版本为1.4.6，解决升级Django版本后mysqlclient版本异常的报错
> declare the version of mysqlclient

- meetings/utils/gene_sign_code.py
修复之前遗留的问题，该问题会导致生成的活动签到二维码无法使用
> correct the page to generate a sign code

- meetings/serializers.py
自2022年10月25日后，前端通过wx.getUserInfo无法再获取到真实的用户昵称和头像信息，需调整策略由后端保存、维护用户的昵称、头像等信息，本次改动仅扩展 userinfo/<int:pk>/ 接口的字段，使前端在用户登录后能获取到用户昵称、头像以及openid
> show users' nickname, avatar and openid to frontend

- Dockerfile
- requirements.txt
由于openeuler-21.03已归档，导致当前基础镜像不可用，将其切换至22.03并修复依赖安装问题
> update base image and satisfy requirements

- meetings/management/commands/handle_recordings.py
鉴于OBS对象元数据中的attenders使用率低、服务已提供查询参会者接口、attenders字段数据可能导致请求头超出限制等因素，OBS对象元数据不再存储参会者真实数据
> The metadata no longer stores participant information

- Dockerfile
- requirements.txt
由于openeuler/openeuler:21.03不再维护，将基础镜像升级为较稳定的openeuler/openeuler:22.03，并处理相应的包版本冲突
> update base image version from 21.03 to 22.03

- opengauss_meetings/settings.py
移除XFrameOptionsMiddleware中间件，该中间件的作用是给response添加header "X-Frame-Options"， 但目前前端已统一配置，需要后端移除该header避免重复
> remove XFrameOptionsMiddleware

- meetings/management/commands/handle_recordings.py
- meetings/management/commands/upload_to_bilibili.py
由于huaweicloud-sdk-python-obs提供的listObjects方法最大可获取对象数为1000，需修改获取策略以获取全量对象，文档参考https://support.huaweicloud.com/sdk-python-devg-obs/obs_22_0805.html
下图给出了修改前后的对比
> get all bucket objects

- meetings/serializers.py
1. 登录时防止刷新的access不一致，额外返回用户对隐私声明同意的状态
2. 清除活动相关接口无用返回
> remove useless returns from interfaces

- meetings/__init__.py
- requirements.txt
1. Django版本从2.2更新至2.2.28后，会出现mysqlclient版本被识别为PyMySQL版本的问题，需声明版本信息
2. 由于PyCrypto存在未修复的漏洞，使用pycryptodome替代PyCrypto
> patch for mysqlclient version

- mindspore_meetings/settings.py
因WAF已进行了X-Frame设置，移除XFrameOptionsMiddleware
> remove X-Frame options

- meetings/views.py
由于openGauss官网前端做了中英文两版，为解决在英文版登录后回调到中文版的问题，需要额外添加中英文官网两个回调地址（已在第三方应用添加），允许前端传入language字段，使Gitee Oauth2全流程的重定向地址保持一致
> redirect by language

- app_meeting_server/utils/handle_recordings.py
如图，当welink会议的录像时间超过3小时，录像会按每3小时分片
在通过confUUID查询welink录像的下载链接时，无法清晰地了解哪条对应与上图的分片对应，通过多次查询下载后，确认查询结果是按视频的生成时间逆序排序，即查询结果的最后一项对应录像的第一片切片，即需要下载的片段
> download the first piece of welink recordings

- app_meeting_server/apps/mindspore/views.py
- app_meeting_server/apps/openeuler/utils/welink_apis.py
- app_meeting_server/apps/openeuler/views.py
- app_meeting_server/apps/opengauss/utils/welink_apis.py
- app_meeting_server/apps/opengauss/views.py
1. 修改鉴权失败场景的状态码与描述
2. 获取会议参会者返回调用真实的状态码
具体的状态码和返回值如下
腾讯会议获取参会者异常：
(400, {'error_info': {'error_code': 190004, 'new_error_code': 1008190004, 'message': 'illegal meeting_id, must be nmeric characters'}})
zoom会议获取参会者异常：
(404, {'code': 3001, 'message': 'Meeting does not exist: 9xxxxxxxxxx.'})
welink会议授权失败：
(401, {'message': 'UnAuthorized'})
> return the true status when getting participants
